server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medshare
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernat:
      ddl-auto: update
      show-sqi: true
      properties:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true